Fix problem caused by upgrade to Postgres 10.
In Postgres 10 we get the following error for :

update planex set plannr = cast((regexp_matches("project_code", '^(\d{5})$'))[1] as integer);x

ERROR:  set-returning functions are not allowed in UPDATE
LINE 1: update planex set plannr = cast((regexp_matches("project_cod...
                                         ^
SQL state: 0A000
Character: 34

The solution is to replace regexp_matches with the new regexp_match